name: PrBuild
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        shell: bash
        run: |
          # Build everything
          dotnet publish MBM-Mods.sln -c Release

      - name: Report Status
        uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          name: Dotnet Build Check
          token: ${{ secrets.GITHUB_TOKEN }}
          conclusion: ${{ job.status }}
