name: PrBuild
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish MBM-Mods.sln -c Release --no-restore
